import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
        <nav
          className="navbar navbar-expand-lg bg-body-tertiary"
          style={{ backgroundColor: "black" }}
        >
          <div className="container-fluid">
            <a className="navbar-brand" href="home">
              Home
            </a>
            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>
            <div
              className="collapse navbar-collapse"
              id="navbarSupportedContent"
            >
              <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                <li className="nav-item">
                  <a
                    className="nav-link active"
                    aria-current="page"
                    href="dashboard"
                  >
                    Dashboard
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="contact">
                    Contact
                  </a>
                </li>
                <li className="nav-item">
                  <a
                    className="nav-link"
                    href="about"
                  >
                    About
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link disabled" aria-disabled="true">
                    Profile
                  </a>
                </li>
              </ul>
              <form className="d-flex" role="search">
                <input
                  className="form-control me-2"
                  type="search"
                  placeholder="Search"
                  aria-label="Search"
                />
                <button className="btn btn-outline-success" type="submit">
                  Search
                </button>
              </form>
            </div>
          </div>
        </nav>
        <div className="d-flex">
          <div
            className="bg-dark text-white p-3 d-flex flex-column"
            style={{ width: "260px" ,height:"495px"}}
          >
            <div className="d-flex mb-4">
              <span className="fs-5 fw-semibold" style={{marginLeft:"70px"}}>Sidebar</span>
            </div>
            <ul className="nav nav-pills flex-column mb-auto gap-1">
              <li className="nav-item">
                <a
                  href="home"
                  className="nav-link active text-white d-flex align-items-center"
                >
                  <i className="bi bi-house me-2"></i> Home
                </a>
              </li>
              <li className="nav-item">
                <a
                  href="dashboard"
                  className="nav-link text-white d-flex align-items-center"
                >
                  <i className="bi bi-speedometer2 me-2"></i> Dashboard
                </a>
              </li>
              <li className="nav-item">
                <a
                  href="contact"
                  className="nav-link text-white d-flex align-items-center"
                >
                  <i className="bi bi-cart me-2"></i> Contact
                </a>
              </li>
              <li className="nav-item">
                <a
                  href="about"
                  className="nav-link text-white d-flex align-items-center"
                >
                  <i className="bi bi-box-seam me-2"></i> About
                </a>
              </li>
              <li className="nav-item">
                <a
                  href="#"
                  className="nav-link text-white d-flex align-items-center"
                >
                  <i className="bi bi-people me-2"></i> Profile
                </a>
              </li>
            </ul>
            <hr className="text-secondary mt-auto" />
            <div className="dropdown">
              <a
                href="#"
                className="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                data-bs-toggle="dropdown"
              >
                <img
                  src="https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/nextjs-icon.png"
                  className="rounded-circle me-2"
                  width="32"
                  height="32"
                />
                <strong>mdo</strong>
              </a>
            </div>
          </div>
          {children}
        </div>
        <footer className="bg-body-tertiary text-center text-lg-start">
  <div className="text-center p-3" style={{backgroundColor: "rgba(0, 0, 0, 0.05)"}}>
    © 2026 Copyright: 
    <a className="text-body" href="https://mdbootstrap.com/">Bhadania Ronit</a>
  </div>
</footer>
      </body>
    </html>
  );
}
