// const path = require('path')

// console.log("Directory Name:"+__dirname)
// console.log("Directory Name:"+path.dirname("E:\\Back End Web Technology\\Lab-4\\Path.js"))
// console.log("File Name:"+path.basename("E:\\Back End Web Technology\\Lab-4\\Path.js"))
// console.log("File Name/Full Path:"+__filename)
// console.log("File Extension:"+path.extname("E:\\Back End Web Technology\\Lab-4\\Path.js"))
// console.log("Join Path:"+path.join("users","ronit","documents","project"))
// console.log("Normalised Path:"+path.normalize("/folder/subfolder/../docs"))
// console.log("Check Absolute Path:"+path.isAbsolute("E:\\Back End Web Technology\\Lab-4\\Path.js"))
// console.log("Relative Path:"+path.relative("E:\\Back End Web Technology\\Lab-4\\Path.js","E:\\Back End Web Technology\\Lab-7\\App.js"))

// const os = require('os')
// console.log(os.version())
// console.log(os.release())
// console.log(os.platform())
// console.log(os.arch())
// console.log(os.totalmem()/(1024*1024*1024))
// console.log(os.freemem()/(1024*1024*1024))
// console.log(os.hostname())
// console.log(os.uptime())
// console.log(os.cpus())
// console.log(os.networkInterfaces())