import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./layout.css"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="site-header">
          <div className="top-text">
            EVERYTHING IS PERSONAL. INCLUDING THIS BLOG.
          </div>

          <h1 className="site-title">Train of Thought</h1>

          <nav className="navbar">
            <ul className="nav-left">
              <li>
                <a href="#" className="active">
                  Home
                </a>
              </li>
              <li>
                <a href="#">About</a>
              </li>
              <li>
                <a href="#">My Blog</a>
              </li>
              <li>
                <a href="#">Contact</a>
              </li>
            </ul>

            <ul className="nav-right">
              <li>
                <i className="fa-solid fa-magnifying-glass"></i>
              </li>
              <li>
                <i className="fa-brands fa-facebook-f"></i>
              </li>
              <li>
                <i className="fa-brands fa-instagram"></i>
              </li>
              <li>
                <i className="fa-brands fa-twitter"></i>
              </li>
              <li>
                <i className="fa-brands fa-pinterest-p"></i>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
